#YAML
n_processes: 4

# dataset dependent parameters
fr : 3.5             # imaging rate in frames per second
decay_time : 1.5    # length of a typical transient in seconds
# note the lower than usual spatial resolution here
#max_shift_um : [12., 12.]       # maximum shift in um
#patch_motion_um : 100, 100  # patch size for non-rigid correction in um

# motion correction parameters
pw_rigid : True       # flag to select rigid vs pw_rigid motion correction
# maximum allowed rigid shift in pixels
max_shifts : [10,10]
# start a new patch for pw-rigid motion correction every x pixels
strides : [35,35]
# overlap between pathes (size of patch in pixels: strides+overlaps)
overlaps : [15,15]
# maximum deviation allowed for patch with respect to rigid shifts
max_deviation_rigid : 3


# parameters for source extraction and deconvolution
p : 0                    # order of the autoregressive system
nb : 3                  # number of global background components, if positive, otherwise ring model with settings
# nb=0 : return background as b and W
# nb=-1 : return full rank background B
# nb<-1: don't return background
merge_thr : 0.7       # merging threshold, max correlation allowed
rf : 30                  # half-size of the patches in pixels. e.g., if rf=25, patches are 50x50
stride_cnmf : 15          # amount of overlap between the patches in pixels
K : 16                    # upper bound on components per patch
gSig : [3, 3]            # gaussian width of a 2D gaussian kernel, which approximates a neuron
#gSiz : [11, 11]     # average diameter of a neuron, in general 4*gSig+1
border_pix: 20 # number of pixels to not consider in the borders)

method_init : greedy_roi   # initialization method (if analyzing dendritic data using 'sparse_nmf'), for standard 2p use greedy_roi, for 1p use corr_pnr


ssub : 1                     # spatial subsampling during initialization, increase if you have memory problems
tsub : 1                     # temporal subsampling during intialization, increase if you have memory problems
center_psf : False      # set to true if there is strong background
low_rank_background : True  # None leaves background of each patch intact, True performs global low-rank approximation if gnb>0
#nb_patch : 1        # number of background components (rank) per patch if nb>0, else it is set automatically (default 1)
min_corr : .6       # min peak value from correlation image (for corr_pnr)
min_pnr : 6        # min peak to noise ration from PNR image (for corr_pnr)
ssub_B : 2          # additional downsampling factor in space for background (for corr_pnr)
ring_size_factor : 1.4  # radius of ring is gSiz*ring_size_factor

#only_init : True 

update_background_components : True # sometimes setting to False improve the results


# quality parameters
# the components are evaluated in three ways:
#   a) the shape of each component must be correlated with the data
#   b) a minimum peak SNR is required over the length of a transient
#   c) each shape passes a CNN based classifier
min_SNR : 1 # signal to noise ratio for accepting a component
rval_thr : 0.5  # space correlation threshold for accepting a component; lower -> more components accepted
use_cnn : False # use CNN classifier on spatial components
min_cnn_thr : 0.9  # threshold for CNN based classifier
cnn_lowest : 0.1 # neurons with cnn probability lower than this value are rejected
SNR_lowest : .5